### PR TITLE
Fix intersection

### LINKED ISSUE #15: intercepts function doesn't work with perfectly-horizontal intercepting lines
```js
var test_bezier = [0, 1.74, .21, 1.67, .28, 1.32, .28, .86];
var test_line = { p1: { x: -.56, y: .95}, p2: { x: .56, y: .95 } };
var test_curve = new Bezier(test_bezier);
var intersections = test_curve.intersects(test_line);
if(intersections.length === 0) throw new Error('Expected at least one intersection');
```

The test curve and line above definitely intersect. I've checked and rechecked multiple times, including drawing the points (at various scales) onto a canvas. bezier.js fails to return any intersection points.

I've actually got a surfboard shape comprised of a set of bezier curves, and I'm using bezier.js to calculate around 150 slice points along the length of the board, but the intersections returned are very intermittent. I typically assume my code is at fault before assuming a library is at fault, but that test case above seems pretty clear.

### PR DESCRIPTION
**Pull request by stavenko**
This PR fixes #15

Bug occured during float comparison. 
Somehow values like `0.950000000015` weren't greater than `0.95`, and on the other hand weren't equal. 
I have added testcase (in simplest assert I even managed to develop) for this bug as well.

Feel comfortable to ask for edits within this PR.

### CODE REVIEW

File: lib/bezier.js [hunk 1]
```diff
@@ -1091,8 +1091,15 @@
...
       return utils.roots(this.points, line).filter(function(t) {
         var p = self.get(t);
-        return (mx <= p.x && p.x <= MX && my <= p.y && p.y <= MY);
+        return between(p.x, mx, MX) && between(p.y, my, MY);
       });
+      function between(x, m, M){ 
+        return (m <= x && x <= M) || fEq(x, m) || fEq(x, M); 
+      }
+      function fEq(a,b,precision) { 
+        if(!precision) precision = 1e-6;
```
Comment (Pomax) [inline lib/bezier.js]: I'd prefer we keep this explicit, so `0.000001`

File: lib/bezier.js [hunk 2]
```diff
@@ -1091,8 +1091,15 @@
           self=this;
       return utils.roots(this.points, line).filter(function(t) {
         var p = self.get(t);
-        return (mx <= p.x && p.x <= MX && my <= p.y && p.y <= MY);
+        return between(p.x, mx, MX) && between(p.y, my, MY);
       });
+      function between(x, m, M){ 
+        return (m <= x && x <= M) || fEq(x, m) || fEq(x, M); 
+      }
+      function fEq(a,b,precision) {
```
Comment (Pomax) [inline lib/bezier.js]: can we rename this to a more descriptive function name? maybe `approx` or something?

**Comment by Pomax** [comment]
Hm, wait. First off: nice! Looks pretty good to me, although I don't see this happening in any of the browsers I'm trying this on. The example you give in your comment at least always shows that "slightly larger than 0.95" as bigger than 0.95, so while this solves the problem of intersections not being found properly, this might solve the symptom rather than the underlying problem.

Do you have a (set of) number(s), either straight up or with the maths operations that yield them through compound IEEE float errors, that demonstrate that there are pairs of numbers (X,Y) where logically X<Y, but the engine running them gets this equality test wrong?

Because that'd be a genuine browser JS engine bug, which we should report to the browser builder(s).

**Comment by stavenko** [comment]
Good point. I'll try prepare testcase later.

**Comment by stavenko** [comment]
So. I wasn't attantive enough.
Here's the example:

    var t = 0.9336954111478684
    var mt = 1-t;
    var p = [ 
      {x:0, y:1.74},
      {x:0.21, y:1.67},
      {x:0.28, y:1.32},
      {x:0.28, y:0.86}
    ]   
    
    
    var mt2 = mt*mt,
        t2 = t*t,
        a,b,c,d = 0;
    var a = mt2*mt;
    var b = mt2*t*3;
    var c = mt*t2*3;
    var d = t*t2;
     var p = { 
      x: a*p[0].x + b*p[1].x + c*p[2].x + d*p[3].x,
      y: a*p[0].y + b*p[1].y + c*p[2].y + d*p[3].y
    };  
    
    var a = [ -0.56, 0.57, 0.95, 0.95 ];
    var mx = -0.56;
    var MX = 0.57;
    var my = 0.95;
    var MY = 0.95;
    
    console.log(mx <= p.x && p.x <= MX);
    console.log(my <= p.y && p.y <= MY, my, p.y, MY);

And here's output:

    $ node smallTest.js 
    true
    false 0.95 0.9500000000000015 0.95

So `p.y` is slightly bigger that `MY`, and certanly not in [0.95, 0.95]. This is why this code doesn't work.

**Comment by stavenko** [comment]
Hi again.
Do you mind to merge or reject this request? I actually would like to use your lib, and I need this case to be solved for my work.

**Comment by Pomax** [comment]
I only have one day in the week to properly work on private projects, and Thursday's it, so I will get this merged in today.

**Comment by Pomax** [comment]
let me merge this in, then make sure that test gets put on top, after that I'll spin a new version tag and push to npm

**Comment by Pomax** [comment]
v1.4.0 is now on npm.

**Comment by stavenko** [comment]
Great. Thank you! :)
